name: Push Events by giving inputs
on:
  workflow_dispatch:
    inputs:
      input1:
        description: This is the name of the user
        required: true
        default: Pranay
jobs:
  show-info:
      runs-on: ubuntu-latest
      steps:
      # - name: Checkout Repository
      #   uses: actions/checkout@v4
      - name: info
        run: |
          # echo "This is the Open issues trigger workflow"
          echo "Hello world ${{ github.event.inputs.input1 }}"
