name: Push Events on open issues
on:
  issues:
    types: opened
jobs:
  show-info:
      runs-on: ubuntu-latest
      steps:
      # - name: Checkout Repository
      #   uses: actions/checkout@v4
      - name: info
        run: |
          echo "This is the Open issues trigger workflow"
          echo "Hello world"
