name: Manual Events
on:
  workflow_dispatch:
jobs:
  show-info:
      runs-on: ubuntu-latest
      steps:
      # - name: Checkout Repository
      #   uses: actions/checkout@v4
      - name: info
        run: |
          echo "This is the first workflow"
          echo "Hello world"
