name: Matrix Configurations
on:
  push:
    branches: main
jobs:
  build:
    strategy:
      matrix:
        age: [22,20]
        name: ["pranay,"teja"]
    runs-on: ubuntu-22.04
    steps:
      - name: Prining name and ages
        run: |
          echo "The name is ${{ matrix.name}} and the age is ${{ matrix.age }}"
        
